[versions]
activityVersion = "1.9.3"
androidGradlePlugin = "8.10.1"
androidDeviceNamesVersion = "2.1.1"
annotationVersion = "1.9.1"
appcompatVersion = "1.7.0"
constraintlayoutVersion = "2.2.0"
core = "5.2.1"
coreSplashscreenVersion = "1.0.1"
coreVersion = "1.15.0"
materialVersion = "1.12.0"

[libraries]
android-device-names = { module = "com.jaredrummler:android-device-names", version.ref = "androidDeviceNamesVersion" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
activity = { module = "androidx.activity:activity", version.ref = "activityVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core = { module = "androidx.core:core", version.ref = "coreVersion" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "core" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }

